# Generated by Django 3.0.2 on 2021-11-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=255)),
                ('product_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_expires', models.CharField(max_length=100)),
                ('product_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('cost_price', models.CharField(max_length=255)),
                ('date_purchase', models.DateTimeField(auto_now_add=True)),
                ('product_description', models.TextField(max_length=255)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
        ),
    ]
