# Generated by Django 3.0.2 on 2021-12-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField(auto_now_add=True, null=True)),
                ('comments', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('line_one_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('line_one_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_one_selling_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_one_total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_one_total_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('line_one_expires', models.DateField()),
                ('line_two_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('line_two_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_two_selling_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_two_total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_two_total_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('line_two_expires', models.DateField()),
                ('line_three_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('line_three_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_three_selling_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_three_total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_three_total_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('line_three_expires', models.DateField()),
                ('line_four_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('line_four_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_four_selling_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_four_total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_four_total_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('line_four_expires', models.DateField()),
                ('line_five_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('line_five_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_five_selling_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_five_total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('line_five_total_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('line_five_expires', models.DateField()),
                ('total', models.IntegerField(blank=True, default='0', null=True)),
                ('balance', models.IntegerField(blank=True, default='0', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Proforma Invoice', 'Proforma Invoice'), ('Invoice', 'Invoice')], default='', max_length=50, null=True)),
                ('line_five_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product5', to='product.Product')),
                ('line_four_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product4', to='product.Product')),
                ('line_one_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product1', to='product.Product')),
                ('line_three_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product3', to='product.Product')),
                ('line_two_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product2', to='product.Product')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SupplierName', to='supplier.Supplier')),
                ('phone_number', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
