# Generated by Django 3.0.2 on 2021-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_phone', models.CharField(max_length=100)),
                ('supplier_email', models.EmailField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
    ]
